export const salonPlaceholderDefaults: Record<string, string> = {
  NOM_SALON: "Atelier Lumière",
  SPECIALITE: "Coiffure & soins",
  VILLE: "Paris",
  COLOR_PRIMARY: "#2c1810",
  COLOR_PRIMARY_DARK: "#1a0f0a",
  COLOR_ACCENT: "#c9a87c",
  COLOR_BG: "#faf8f5",
  LIEN_RDV: "/login",
  SLOGAN: "L’art de sublimer votre style, dans un cadre chaleureux.",
  ACCROCHE: "Bien plus qu’un salon",
  TEXTE_ABOUT:
    "Notre équipe formée aux dernières techniques vous accueille du mardi au samedi. Produits professionnels, espace détente.",
  SERVICE_1_NOM: "Coupe femme",
  SERVICE_1_PRIX: "45 €",
  SERVICE_1_DESC: "Consultation + shampoing + coupe + brushing.",
  SERVICE_1_DUREE: "45 min",
  SERVICE_2_NOM: "Coupe homme",
  SERVICE_2_PRIX: "28 €",
  SERVICE_2_DESC: "Coupe classique ou dégradé.",
  SERVICE_2_DUREE: "30 min",
  SERVICE_3_NOM: "Coupe + brushing",
  SERVICE_3_PRIX: "55 €",
  SERVICE_3_DESC: "Pour une mise en forme complète.",
  SERVICE_3_DUREE: "60 min",
  SERVICE_4_NOM: "Coloration",
  SERVICE_4_PRIX: "À partir de 65 €",
  SERVICE_4_DESC: "Sur devis selon longueur.",
  SERVICE_4_DUREE: "90 min",
  SERVICE_5_NOM: "Soin profond",
  SERVICE_5_PRIX: "15 €",
  SERVICE_5_DESC: "Masque réparateur.",
  SERVICE_5_DUREE: "30 min",
  SERVICE_6_NOM: "Barbe",
  SERVICE_6_PRIX: "15 €",
  SERVICE_6_DESC: "Taille et finitions.",
  SERVICE_6_DUREE: "20 min",
  TEAM_1_NOM: "Léa",
  TEAM_1_ROLE: "Artiste coloriste",
  TEAM_1_DESC: "Spécialiste balayages et coupes tendance.",
  TEAM_2_NOM: "Marc",
  TEAM_2_ROLE: "Coiffeur barbier",
  TEAM_2_DESC: "Coupe homme et entretien barbe.",
  TEAM_3_NOM: "Sarah",
  TEAM_3_ROLE: "Styliste",
  TEAM_3_DESC: "Coiffures de soirée et conseils image.",
  AVIS_1_TEXTE: "« Accueil top, coupe exactement comme je voulais. »",
  AVIS_1_AUTEUR: "— Camille",
  AVIS_2_TEXTE: "« Meilleur salon du quartier. »",
  AVIS_2_AUTEUR: "— Thomas",
  AVIS_3_TEXTE: "« Coloration naturelle, je recommande. »",
  AVIS_3_AUTEUR: "— Marie",
  FAQ_1_Q: "Dois-je réserver ?",
  FAQ_1_A: "Oui, créneaux sur ce site ou par téléphone.",
  FAQ_2_Q: "Produits utilisés ?",
  FAQ_2_A: "Gammes professionnelles sans ammoniaque sur demande.",
  FAQ_3_Q: "Annulation ?",
  FAQ_3_A: "Merci de prévenir 24 h à l’avance.",
  FAQ_4_Q: "Première visite ?",
  FAQ_4_A: "Prévoir 15 min de plus pour le diagnostic cheveux.",
  FAQ_5_Q: "Paiement ?",
  FAQ_5_A: "CB, espèces, titres restaurant.",
  TELEPHONE_RAW: "+33142385678",
  TELEPHONE: "01 42 38 56 78",
  ADRESSE: "14 rue des Petites Écuries, 75010 Paris",
  HORAIRES: "Mar–Sam 10h–19h",
};
