/** Placeholders du template artisan/index.html — valeurs par défaut vitrine. */
export const artisanPlaceholderDefaults: Record<string, string> = {
  NOM_ENTREPRISE: "Dupont Rénovation",
  NOM_ENTREPRISE_COURT: "Dupont",
  SPECIALITE: "Plomberie & chauffage",
  VILLE: "Lyon",
  COLOR_ACCENT: "#c45c26",
  COLOR_ACCENT_DARK: "#9a4218",
  COLOR_BG: "#faf7f4",
  TELEPHONE: "06 12 34 56 78",
  TELEPHONE_RAW: "+33612345678",
  EMAIL: "contact@dupont-renovation.fr",
  ADRESSE: "12 rue des Artisans, 69001 Lyon",
  BADGE: "Artisan certifié · 15 ans d'expérience",
  TITRE_HERO: 'Votre <span class="accent">plombier</span> de confiance à Lyon',
  SOUS_TITRE_HERO:
    "Dépannage urgent, rénovation salle de bain, chauffage : intervention rapide, devis gratuit et travail garanti.",
  STAT_1_VAL: "500+",
  STAT_1_LABEL: "chantiers",
  STAT_2_VAL: "24h",
  STAT_2_LABEL: "urgences",
  STAT_3_VAL: "10 ans",
  STAT_3_LABEL: "garantie",
  HERO_IMAGE:
    "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80",
  TITRE_SERVICES: "Ce que nous faisons pour vous",
  DESC_SERVICES:
    "Une équipe qualifiée pour tous vos besoins en plomberie, chauffage et rénovation.",
  SERVICE_1_LUCIDE: "droplets",
  SERVICE_1_NOM: "Dépannage",
  SERVICE_1_DESC: "Fuites, WC bouchés, panne chauffe-eau — intervention sous 24h.",
  SERVICE_2_LUCIDE: "flame",
  SERVICE_2_NOM: "Chauffage",
  SERVICE_2_DESC: "Installation et entretien chaudière, radiateurs, plancher chauffant.",
  SERVICE_3_LUCIDE: "bath",
  SERVICE_3_NOM: "Salle de bain",
  SERVICE_3_DESC: "Création et rénovation complète, douche à l'italienne, robinetterie.",
  SERVICE_4_LUCIDE: "wrench",
  SERVICE_4_NOM: "Rénovation",
  SERVICE_4_DESC: "Reprise de réseaux, mise aux normes, conseil matériaux.",
  SERVICE_5_LUCIDE: "shield-check",
  SERVICE_5_NOM: "Détection",
  SERVICE_5_DESC: "Recherche de fuite sans casse, caméra, diagnostic précis.",
  SERVICE_6_LUCIDE: "clock",
  SERVICE_6_NOM: "Contrats",
  SERVICE_6_DESC: "Entretien annuel, contrats pro pour copropriétés et pros.",
  TITRE_REALISATIONS: "Avant / après",
  DESC_REALISATIONS: "Quelques chantiers récents chez nos clients.",
  REAL_1_TITRE: "Salle de bain complète",
  REAL_1_DESC: "Douche à l'italienne, meuble sur mesure — Lyon 6e",
  REAL_2_TITRE: "Réseau sanitaire",
  REAL_2_DESC: "Reprise totale appartement — Villeurbanne",
  TITRE_ZONE: "Où intervenons-nous ?",
  DESC_ZONE:
    "Lyon et première couronne : déplacement rapide pour dépannage et devis.",
  ZONE_1: "Lyon centre",
  ZONE_2: "Villeurbanne",
  ZONE_3: "Caluire",
  ZONE_4: "Écully",
  ZONE_5: "Bron",
  ZONE_6: "Saint-Fons",
  ZONE_7: "Oullins",
  ZONE_8: "Francheville",
  TITRE_GARANTIES: "Pourquoi nous faire confiance",
  GARANTIE_1_TITRE: "Réactivité",
  GARANTIE_1_DESC: "Créneaux urgents et rappel sous 2h en journée.",
  GARANTIE_2_TITRE: "Assurances",
  GARANTIE_2_DESC: "RC pro à jour, décennale sur travaux.",
  GARANTIE_3_TITRE: "Devis clair",
  GARANTIE_3_DESC: "Prix annoncé avant intervention, pas de mauvaise surprise.",
  GARANTIE_4_TITRE: "Savoir-faire",
  GARANTIE_4_DESC: "Artisan qualifié, avis clients vérifiés.",
  TITRE_AVIS: "Ils nous ont fait confiance",
  AVIS_1_TEXTE:
    "Intervention un dimanche soir pour une fuite d'eau — pro et rapide.",
  AVIS_1_AUTEUR: "Marie L.",
  AVIS_1_DETAIL: "Lyon 3e",
  AVIS_2_TEXTE: "Réfection salle de bain impeccable, équipe soigneuse.",
  AVIS_2_AUTEUR: "Thomas R.",
  AVIS_2_DETAIL: "Caluire",
  AVIS_3_TEXTE: "Devis respecté, délais tenus. Je recommande.",
  AVIS_3_AUTEUR: "Sophie M.",
  AVIS_3_DETAIL: "Villeurbanne",
  TITRE_FAQ: "Questions fréquentes",
  FAQ_1_Q: "Proposez-vous un devis gratuit ?",
  FAQ_1_A: "Oui, déplacement et devis sont gratuits et sans engagement sur Lyon et proche banlieue.",
  FAQ_2_Q: "Intervenez-vous en urgence ?",
  FAQ_2_A: "Oui, nous réservons des créneaux pour les fuites et pannes urgentes.",
  FAQ_3_Q: "Êtes-vous assurés ?",
  FAQ_3_A: "Oui, responsabilité civile professionnelle et garantie décennale selon travaux.",
  FAQ_4_Q: "Quels moyens de paiement ?",
  FAQ_4_A: "Chèque, virement, carte ; acompte possible pour gros chantiers.",
  CTA_TITRE: "Un projet ? Un dépannage ?",
  CTA_DESC: "Appelez-nous ou demandez un rappel — réponse rapide garantie.",
  FOOTER_DESC: "Plomberie · Chauffage · Rénovation",
  /** Lien formulaire devis (slug = même que fiche entreprise seed) */
  LINK_DEVIS: "/devis?e=mon-entreprise",
};
