export const praticienPlaceholderDefaults: Record<string, string> = {
  NOM_PRATICIEN: "Camille Martin",
  SPECIALITE: "Sophrologue",
  VILLE: "Lyon",
  COLOR_BG: "#f8f6f3",
  COLOR_BG_ALT: "#f0ebe4",
  COLOR_BG_DARK: "#1c1917",
  COLOR_ACCENT: "#6b7f5a",
  COLOR_CTA: "#5a6b4d",
  COLOR_TEXT: "#292524",
  COLOR_TEXT_DARK: "#1c1917",
  HERO_IMAGE_URL:
    "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=1600&q=80",
  CTA_PRIMARY_URL: "/login",
  CTA_TOPBAR: "Prendre RDV",
  CTA_PRIMARY_LABEL: "Espace client & RDV",
  CTA_SECONDARY_URL: "tel:+33612345678",
  CTA_SECONDARY_LABEL: "Appeler",
  TITRE_HERO: "Retrouver calme, sommeil et confiance",
  SOUS_TITRE_HERO:
    "Séances individuelles en cabinet ou à distance. Première séance découverte sur rendez-vous.",
  MANIFESTO_TEXTE:
    "« Chaque personne avance à son rythme. Mon rôle est de vous offrir un cadre sûr pour déposer le stress et retrouver des ressources. »",
  PRACTITIONER_IMAGE_URL:
    "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80",
  TITRE_PRACTICIEN: "Votre praticienne",
  TITRE_PRACTICIEN_TAG: "Rencontre",
  TEXTE_PRACTICIEN:
    "Diplômée et membre d’association professionnelle, j’accompagne depuis plus de dix ans adultes et adolescents.",
  TEXTE_PRACTICIEN_2: "Cabinet accessible PMR · stationnement à proximité.",
  TITRE_SERVICES_TAG: "Accompagnement",
  TITRE_SERVICES: "Les séances",
  INTRO_SERVICES:
    "Durée indicative 60 min. Tarifs indicatifs — devis sur demande.",
  SEANCE_1_IMAGE_URL:
    "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=400&q=80",
  SEANCE_1_NOM: "Sophrologie individuelle",
  SEANCE_1_PRIX: "60 €",
  SEANCE_1_DESC: "Stress, sommeil, préparation mentale.",
  SEANCE_2_IMAGE_URL:
    "https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=400&q=80",
  SEANCE_2_NOM: "Première séance découverte",
  SEANCE_2_PRIX: "50 €",
  SEANCE_2_DESC: "Entretien + pratique guidée courte.",
  SEANCE_3_IMAGE_URL:
    "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=400&q=80",
  SEANCE_3_NOM: "À distance (visio)",
  SEANCE_3_PRIX: "55 €",
  SEANCE_3_DESC: "Même cadre qu’en présentiel, depuis chez vous.",
  TITRE_AVIS_TAG: "Témoignages",
  TITRE_AVIS: "Elles et ils en parlent",
  AVIS_1: "« J’ai retrouvé le sommeil en quelques séances. »",
  AVIS_1_AUTEUR: "— Marie, Lyon",
  AVIS_2: "« Écoute bienveillante, sans jugement. »",
  AVIS_2_AUTEUR: "— Thomas",
  AVIS_3: "« Je recommande pour le stress au travail. »",
  AVIS_3_AUTEUR: "— Sophie",
  TITRE_FAQ_TAG: "FAQ",
  TITRE_FAQ: "Questions fréquentes",
  FAQ_1_Q: "Combien de séances ?",
  FAQ_1_R: "Selon votre objectif, en moyenne 4 à 8 séances.",
  FAQ_2_Q: "Remboursement ?",
  FAQ_2_R: "Certaines mutuelles remboursent la sophrologie — renseignez-vous auprès de la vôtre.",
  FAQ_3_Q: "Annulation ?",
  FAQ_3_R: "Merci de prévenir 24 h à l’avance.",
  TITRE_CTA_TAG: "Contact",
  TITRE_CTA: "Prendre rendez-vous",
  TEXTE_CTA: "Connexion pour réserver un créneau ou nous écrire.",
  TELEPHONE: "06 12 34 56 78",
  EMAIL: "contact@exemple-sophro.fr",
  ADRESSE: "12 rue des Lilas, 69003 Lyon",
  FOOTER_DESC: "Sophrologue certifiée · Lyon",
};
