export const immobilierPlaceholderDefaults: Record<string, string> = {
  NOM_AGENCE: "Horizon Immobilier",
  SPECIALITE: "Achat · Vente · Location",
  VILLE: "Lyon",
  COLOR_ACCENT: "#c4a574",
  COLOR_ACCENT_DARK: "#a68452",
  COLOR_BG: "#f8f6f2",
  HERO_IMAGE:
    "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1920&q=80",
  TITRE_HERO: "Trouvez votre bien idéal",
  SOUS_TITRE_HERO:
    "Une équipe à votre écoute pour acheter, vendre ou louer en toute confiance.",
  STAT_1_VAL: "450",
  STAT_1_LABEL: "biens vendus",
  STAT_2_VAL: "28",
  STAT_2_LABEL: "ans d’expérience",
  STAT_3_VAL: "120",
  STAT_3_LABEL: "biens en gestion",
  STAT_4_VAL: "4.9",
  STAT_4_LABEL: "avis clients",
  TITRE_BIENS: "Sélection du moment",
  DESC_BIENS: "Appartements et maisons — mandats exclusifs et partagés.",
  BIEN_1_TYPE: "À vendre",
  BIEN_1_PRIX: "485 000 €",
  BIEN_1_TITRE: "T4 avec terrasse",
  BIEN_1_LIEU: "Lyon 6e",
  BIEN_1_SURFACE: "98 m²",
  BIEN_1_CHAMBRES: "3 ch.",
  BIEN_2_TYPE: "À louer",
  BIEN_2_PRIX: "1 250 € / mois",
  BIEN_2_TITRE: "T3 rénové",
  BIEN_2_LIEU: "Villeurbanne",
  BIEN_2_SURFACE: "72 m²",
  BIEN_2_CHAMBRES: "2 ch.",
  BIEN_3_TYPE: "À vendre",
  BIEN_3_PRIX: "890 000 €",
  BIEN_3_TITRE: "Maison avec jardin",
  BIEN_3_LIEU: "Caluire",
  BIEN_3_SURFACE: "145 m²",
  BIEN_3_CHAMBRES: "5 p.",
  ESTIMATION_TITRE: "Estimation gratuite",
  ESTIMATION_DESC:
    "Confiez-nous votre bien : analyse de marché et fourchette sous 48 h.",
  TELEPHONE_RAW: "+33472123456",
  TITRE_SERVICES: "Nos services",
  DESC_SERVICES:
    "De la recherche du bien jusqu’à la signature, nous vous accompagnons.",
  SERVICE_1_NOM: "Achat",
  SERVICE_1_DESC: "Recherche ciblée, visites, négociation, financement.",
  SERVICE_2_NOM: "Vente",
  SERVICE_2_DESC: "Estimation, mandat, diffusion, visites, acte authentique.",
  SERVICE_3_NOM: "Location",
  SERVICE_3_DESC: "Gestion locative, états des lieux, sélection locataires.",
  SERVICE_4_NOM: "Investissement",
  SERVICE_4_DESC: "Pinel, LMNP, rendement — étude sur mesure.",
  SERVICE_5_NOM: "Viager",
  SERVICE_5_DESC: "Accompagnement juridique et fiscal.",
  SERVICE_6_NOM: "Syndic",
  SERVICE_6_DESC: "Copropriétés — conseil et gestion (selon zone).",
  TITRE_QUARTIERS: "Nous couvrons ces quartiers",
  DESC_QUARTIERS: "Une présence locale forte pour mieux servir acheteurs et vendeurs.",
  QUARTIER_1_NOM: "Lyon Centre",
  QUARTIER_1_BIENS: "24",
  QUARTIER_2_NOM: "Villeurbanne",
  QUARTIER_2_BIENS: "18",
  QUARTIER_3_NOM: "Caluire",
  QUARTIER_3_BIENS: "12",
  QUARTIER_4_NOM: "Ouest lyonnais",
  QUARTIER_4_BIENS: "31",
  TITRE_EQUIPE: "Votre équipe",
  DESC_EQUIPE: "Négociateurs et administratif à votre disposition.",
  TEAM_1_NOM: "Marc Dubois",
  TEAM_1_ROLE: "Directeur d’agence",
  TEAM_2_NOM: "Julie Martin",
  TEAM_2_ROLE: "Négociatrice senior",
  TEAM_3_NOM: "Thomas Leroy",
  TEAM_3_ROLE: "Conseiller location",
  TITRE_AVIS: "Ils nous font confiance",
  AVIS_1_TEXTE: "« Vente rapide, au prix estimé. Équipe pro et disponible. »",
  AVIS_1_AUTEUR: "Céline R.",
  AVIS_1_DETAIL: "Vente T3 — 2025",
  AVIS_2_TEXTE: "« Nous avons trouvé notre appart en deux semaines. »",
  AVIS_2_AUTEUR: "Famille P.",
  AVIS_2_DETAIL: "Achat",
  AVIS_3_TEXTE: "« Gestion locative sans stress. »",
  AVIS_3_AUTEUR: "Investisseur",
  AVIS_3_DETAIL: "LMNP",
  TITRE_FAQ: "Questions fréquentes",
  FAQ_1_Q: "Comment est fixé le prix de vente ?",
  FAQ_1_A:
    "Nous croisons données de marché, état du bien et délai souhaité pour une fourchette réaliste.",
  FAQ_2_Q: "Honoraires ?",
  FAQ_2_A:
    "Ils sont indiqués dans le mandat ; pas de surprise à la signature.",
  FAQ_3_Q: "Visites sans engagement ?",
  FAQ_3_A: "Oui pour l’achat ; pour la vente un mandat formalise notre mission.",
  FAQ_4_Q: "Délai moyen de vente ?",
  FAQ_4_A: "Variable selon secteur et prix — nous vous donnons une fourchette en amont.",
  CTA_TITRE: "Un projet immobilier ?",
  CTA_DESC: "Prenez rendez-vous en agence ou demandez une estimation.",
  TELEPHONE: "04 72 12 34 56",
  EMAIL: "contact@horizon-immo.fr",
  ADRESSE: "15 rue de la République, 69002 Lyon",
  FOOTER_DESC: "Transactions · Location · Gestion",
};
