export const hotelPlaceholderDefaults: Record<string, string> = {
  NOM_HOTEL: "Hôtel Riviera",
  NOM_HOTEL_COURT: "Riviera",
  CATEGORIE: "Hôtel 4 étoiles",
  VILLE: "Nice",
  ACCROCHE_META: "Piscine, spa et vue mer — réservez au meilleur tarif.",
  COLOR_ACCENT: "#b8860b",
  COLOR_ACCENT_DARK: "#8b6914",
  COLOR_BG: "#faf8f5",
  ETOILES_DISPLAY: "★★★★",
  HERO_IMAGE:
    "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1920&q=80",
  IMAGE_CTA:
    "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1920&q=80",
  TITRE_HERO: "L’art de recevoir face à la mer",
  SOUS_TITRE_HERO:
    "Chambres et suites, petit-déjeuner buffet, spa et piscine à débordement.",
  STAT_1_VAL: "4★",
  STAT_1_LABEL: "Établissement",
  STAT_2_VAL: "48",
  STAT_2_LABEL: "chambres",
  STAT_3_VAL: "9.2",
  STAT_3_LABEL: "note clients",
  STAT_4_VAL: "1930",
  STAT_4_LABEL: "depuis",
  IMAGE_HISTOIRE:
    "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=800&q=80",
  TITRE_HISTOIRE: "Une adresse niçoise",
  DESC_HISTOIRE:
    "Notre maison a accueilli voyageurs et familles depuis près d’un siècle. Rénovée avec respect du patrimoine.",
  CITATION: "« Ici, chaque séjour doit ressembler à une parenthèse. »",
  CHAMBRE_1_NOM: "Chambre Classique",
  CHAMBRE_2_NOM: "Chambre Supérieure",
  CHAMBRE_3_NOM: "Suite vue mer",
  TITRE_CHAMBRES: "Où poser vos valises",
  DESC_CHAMBRES:
    "Du confort essentiel à l’exceptionnel — toutes nos chambres offrent literie haut de gamme et plateau courtoisie.",
  CHAMBRE_1_TYPE: "Standard",
  CHAMBRE_1_IMAGE:
    "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=800&q=80",
  CHAMBRE_1_CAPACITE: "2 pers.",
  CHAMBRE_1_SURFACE: "22 m²",
  CHAMBRE_1_PRIX: "89 €",
  CHAMBRE_2_TYPE: "Supérieure",
  CHAMBRE_2_IMAGE:
    "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80",
  CHAMBRE_2_CAPACITE: "2 pers.",
  CHAMBRE_2_SURFACE: "28 m²",
  CHAMBRE_2_PRIX: "125 €",
  CHAMBRE_3_TYPE: "Suite",
  CHAMBRE_3_IMAGE:
    "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80",
  CHAMBRE_3_CAPACITE: "4 pers.",
  CHAMBRE_3_SURFACE: "55 m²",
  CHAMBRE_3_PRIX: "249 €",
  TITRE_SERVICES: "Services & équipements",
  DESC_SERVICES: "Pensés pour votre confort, du matin au soir.",
  SERVICE_1_LUCIDE: "wifi",
  SERVICE_1_NOM: "Wi‑Fi fibre",
  SERVICE_1_DESC: "Gratuit dans tout l’hôtel.",
  SERVICE_2_LUCIDE: "waves",
  SERVICE_2_NOM: "Piscine",
  SERVICE_2_DESC: "Extérieure chauffée avr.–oct.",
  SERVICE_3_LUCIDE: "coffee",
  SERVICE_3_NOM: "Petit-déjeuner",
  SERVICE_3_DESC: "Buffet & vue mer.",
  SERVICE_4_LUCIDE: "car",
  SERVICE_4_NOM: "Parking",
  SERVICE_4_DESC: "Places sous réservation.",
  SERVICE_5_LUCIDE: "sparkles",
  SERVICE_5_NOM: "Spa",
  SERVICE_5_DESC: "Hammam, soins sur RDV.",
  SERVICE_6_LUCIDE: "concierge-bell",
  SERVICE_6_NOM: "Conciergerie",
  SERVICE_6_DESC: "Transferts, excursions.",
  TITRE_GALERIE: "Ambiance",
  GALERIE_1:
    "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=600&q=80",
  GALERIE_2:
    "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=600&q=80",
  GALERIE_3:
    "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&w=600&q=80",
  GALERIE_4:
    "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=600&q=80",
  GALERIE_5:
    "https://images.unsplash.com/photo-1602002418082-dd44424905cf?auto=format&fit=crop&w=600&q=80",
  TITRE_AVIS: "Avis voyageurs",
  AVIS_1_NOTE: "9.6",
  AVIS_1_PLATEFORME: "Booking",
  AVIS_1_TEXTE: "Emplacement parfait, personnel aux petits soins.",
  AVIS_1_AUTEUR: "Sophie M.",
  AVIS_1_DATE: "Janv. 2026",
  AVIS_2_NOTE: "9.4",
  AVIS_2_PLATEFORME: "Google",
  AVIS_2_TEXTE: "Piscine et petit-déj au top.",
  AVIS_2_AUTEUR: "Marc L.",
  AVIS_2_DATE: "Déc. 2025",
  AVIS_3_NOTE: "9.8",
  AVIS_3_PLATEFORME: "Booking",
  AVIS_3_TEXTE: "Suite vue mer à couper le souffle.",
  AVIS_3_AUTEUR: "Claire D.",
  AVIS_3_DATE: "Nov. 2025",
  CTA_TITRE: "Réservez votre séjour",
  CTA_DESC: "Meilleur tarif garanti en réservant directement.",
  TELEPHONE_RAW: "+33493123456",
  TELEPHONE: "04 93 12 34 56",
  EMAIL: "reservation@hotel-riviera.fr",
  ADRESSE: "18 promenade des Anglais, 06000 Nice",
  FOOTER_DESC: "Hôtel 4★ — Spa — Piscine — Parking",
  /** Lien résa module lodging (slug établissement = seed mon-hotel) */
  LINK_RESA: "/hebergement/chambre/chambre-classique?e=mon-hotel",
};
